### ISSUE TITLE
java 11 support

### ISSUE THREAD

**Issue by hughlunnon** [skydrinker-tox/testcontainers-mailcatcher#3]
Hey

Loving the work on this. How would you feel about backing down the compiled java version to java 8 or 11 (which I think would just be a change to here 

https://github.com/skydrinker-tox/testcontainers-mailcatcher/blob/701655e0bdb6a47f03f38acd0e7e5c11d83c1367/pom.xml#L49

which would make it easier for consumers to use the container on a legacy app? 

Happy to raise a PR if you like

Thanks

Hugh

**Comment by skydrinker-tox** [comment]
Thanks for raising this issue. I'm not big a fan of supporting deprecated frameworks, but it won't cost much to add this. Release is incoming.

**Comment by skydrinker-tox** [comment]
Release 0.9.3 with java 11 support is now published on [maven central](https://central.sonatype.com/artifact/io.github.skydrinker-tox/testcontainers-mailcatcher).
